# Generated by Django 4.2.1 on 2024-05-27 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tblAnimalesTipo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblClientes',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Nombre', models.CharField(max_length=150, null=True, unique=True)),
                ('Direccion', models.CharField(max_length=150, null=True)),
                ('Ciudad', models.CharField(max_length=150, null=True)),
                ('RFC', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Contacto', models.CharField(max_length=150, null=True)),
                ('TelefonoContacto', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblConfiguracion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=150, null=True)),
                ('BaseDeDatos', models.CharField(max_length=150, null=True)),
                ('FechaDescarga', models.DateTimeField(null=True)),
                ('FechaActualizacion', models.DateTimeField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblContenedoresMateriaPrima',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Cliente', models.CharField(max_length=150, null=True)),
                ('Capacidad', models.FloatField(max_length=150, null=True)),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblclientes')),
            ],
        ),
        migrations.CreateModel(
            name='tblContenedoresProductos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Proveedor', models.CharField(max_length=150, null=True)),
                ('Capacidad', models.FloatField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblCorrales',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=150, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
                ('Capacidad', models.FloatField(null=True)),
                ('FechaAsigna', models.DateTimeField(max_length=150, null=True)),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblclientes')),
            ],
        ),
        migrations.CreateModel(
            name='tblEstatus',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblMateriaPrima',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
                ('PrecioUnitario', models.FloatField(null=True)),
                ('Merma', models.FloatField(null=True)),
                ('IDEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus')),
            ],
        ),
        migrations.CreateModel(
            name='tblProductos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
                ('PrecioUnitario', models.FloatField(null=True)),
                ('SeSirve', models.CharField(max_length=15, null=True)),
                ('IDEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus')),
            ],
        ),
        migrations.CreateModel(
            name='tblProveedores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Nombre', models.CharField(max_length=150, null=True, unique=True)),
                ('Direccion', models.CharField(max_length=150, null=True)),
                ('Ciudad', models.CharField(max_length=150, null=True)),
                ('RFC', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Contacto', models.CharField(max_length=150, null=True)),
                ('TelefonoContacto', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblServiciosWeb',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Servicio', models.BooleanField(null=True, verbose_name=True)),
                ('EstadoPago', models.BooleanField(null=True, verbose_name=True)),
                ('FechaVencimiento', models.DateField(null=True)),
                ('Notificacion', models.BooleanField(null=True, verbose_name=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblTecnicos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Tecnico', models.CharField(max_length=150, null=True)),
                ('TecnicoEditor', models.CharField(max_length=150, null=True)),
                ('TecnicoElimino', models.CharField(max_length=150, null=True)),
                ('AreaRegistro', models.CharField(max_length=150, null=True)),
                ('NombreTabla', models.CharField(max_length=150, null=True)),
                ('IDFilaTabla', models.CharField(max_length=150, null=True)),
                ('IDFila', models.CharField(max_length=150, null=True)),
                ('Acciones', models.CharField(max_length=50, null=True)),
                ('AccionesEditado', models.CharField(max_length=50, null=True)),
                ('AccionesEliminado', models.CharField(max_length=50, null=True)),
                ('Fecha', models.DateTimeField(null=True)),
                ('FechaActualizado', models.DateTimeField(null=True)),
                ('FechaEliminado', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblTipoMaterial',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblTipoMov',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblUnidades',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
                ('Abreviacion', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblTolva',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Marca', models.CharField(max_length=15, null=True)),
                ('Modelo', models.CharField(max_length=150, null=True)),
                ('Capacidad', models.IntegerField(null=True)),
                ('Alias', models.CharField(max_length=100, null=True)),
                ('IDEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus')),
                ('IDProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos')),
                ('UdeM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblunidades')),
            ],
        ),
        migrations.CreateModel(
            name='tblTipoPresentacion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
                ('Cantidad', models.FloatField(null=True)),
                ('Visible', models.CharField(max_length=15, null=True)),
                ('UdeM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblunidades')),
            ],
        ),
        migrations.CreateModel(
            name='tblServido',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=15, null=True)),
                ('CantidadSolicitada', models.IntegerField(null=True)),
                ('CantidadServida', models.IntegerField(null=True)),
                ('Prioridad', models.CharField(max_length=100, null=True)),
                ('Fecha', models.DateTimeField(max_length=150, null=True)),
                ('FechaServida', models.DateTimeField(max_length=150, null=True)),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblclientes')),
                ('IDCorral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcorrales')),
                ('IDEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus')),
                ('IDProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos')),
                ('IDTolva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltolva')),
            ],
        ),
        migrations.CreateModel(
            name='tblSalidaProductos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDFolio', models.CharField(max_length=15, null=True)),
                ('cantidad', models.FloatField(null=True)),
                ('referencia', models.IntegerField(null=True)),
                ('fecha', models.DateTimeField(max_length=150, null=True)),
                ('notas', models.CharField(max_length=120, null=True)),
                ('IDAlmacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcontenedoresproductos')),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblclientes')),
                ('IDPresentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltipopresentacion')),
                ('IDProductos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos')),
                ('IDTipoMov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltipomov')),
            ],
        ),
        migrations.CreateModel(
            name='tblSalidaMP',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDFolio', models.CharField(max_length=15, null=True)),
                ('cantidad', models.FloatField(null=True)),
                ('referencia', models.IntegerField(null=True)),
                ('fecha', models.DateTimeField(max_length=150, null=True)),
                ('notas', models.CharField(max_length=120, null=True)),
                ('IDAlmacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcontenedoresmateriaprima')),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblclientes')),
                ('IDMateriaPrima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblmateriaprima')),
                ('IDPresentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltipopresentacion')),
            ],
        ),
        migrations.CreateModel(
            name='tblProductosMateriaPrima',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=15, null=True)),
                ('Porcentaje', models.FloatField(null=True)),
                ('Merma', models.FloatField(null=True)),
                ('IDMateriaPrima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblmateriaprima')),
                ('IDProductos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos')),
            ],
        ),
        migrations.AddField(
            model_name='tblproductos',
            name='IDUnidadMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblunidades'),
        ),
        migrations.CreateModel(
            name='tblOtrosDatosSalXBas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDSalida', models.CharField(max_length=15, null=True)),
                ('Camion', models.CharField(max_length=150, null=True)),
                ('Chofer', models.CharField(max_length=150, null=True)),
                ('Placas', models.CharField(max_length=150, null=True)),
                ('IDOperador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tblOtrosDatosMovMP',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDMovMP', models.CharField(max_length=15, null=True)),
                ('Costo', models.FloatField(null=True)),
                ('Flete', models.FloatField(null=True)),
                ('Maniobra', models.FloatField(null=True)),
                ('Camion', models.CharField(max_length=150, null=True)),
                ('Chofer', models.CharField(max_length=150, null=True)),
                ('Placas', models.CharField(max_length=150, null=True)),
                ('IDOperador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tblOperadores',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Descripcion', models.CharField(max_length=150, null=True)),
                ('IDEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus')),
            ],
        ),
        migrations.CreateModel(
            name='tblMovimientoAnimales',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=15, null=True)),
                ('Fecha', models.DateTimeField(null=True)),
                ('Peso', models.FloatField(null=True)),
                ('NoPartida', models.IntegerField(null=True)),
                ('No_Guia', models.IntegerField(null=True)),
                ('Notas', models.CharField(max_length=150, null=True)),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblclientes')),
                ('IDCorral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcorrales')),
                ('IDMovimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltipomov')),
            ],
        ),
        migrations.AddField(
            model_name='tblmateriaprima',
            name='IDUnidadMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblunidades'),
        ),
        migrations.CreateModel(
            name='tblInventarioInicialesProductos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=15, null=True)),
                ('Cantidad', models.FloatField(null=True)),
                ('Fecha', models.DateTimeField(max_length=150, null=True)),
                ('Notas', models.CharField(max_length=150, null=True)),
                ('IDContenedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcontenedoresproductos')),
                ('IDProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos')),
            ],
        ),
        migrations.CreateModel(
            name='tblInventarioInicialesMP',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=15, null=True)),
                ('Cantidad', models.FloatField(null=True)),
                ('Fecha', models.DateTimeField(max_length=150, null=True)),
                ('Notas', models.CharField(max_length=150, null=True)),
                ('IDContenedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcontenedoresmateriaprima')),
                ('IDMateriaPrima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblmateriaprima')),
            ],
        ),
        migrations.CreateModel(
            name='tblEntradaProductos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDFolio', models.CharField(max_length=15, null=True)),
                ('cantidad', models.FloatField(null=True)),
                ('referencia', models.IntegerField(null=True)),
                ('fecha', models.DateTimeField(max_length=150, null=True)),
                ('notas', models.CharField(max_length=120, null=True)),
                ('IDAlmacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcontenedoresproductos')),
                ('IDPresentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltipopresentacion')),
                ('IDProductos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos')),
                ('IDProveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproveedores')),
                ('IDTipoMov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltipomov')),
            ],
        ),
        migrations.CreateModel(
            name='tblEntradaMP',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDFolio', models.CharField(max_length=15, null=True)),
                ('cantidad', models.FloatField(null=True)),
                ('referencia', models.IntegerField(null=True)),
                ('fecha', models.DateTimeField(max_length=150, null=True)),
                ('notas', models.CharField(max_length=120, null=True)),
                ('IDAlmacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcontenedoresmateriaprima')),
                ('IDMateriaPrima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblmateriaprima')),
                ('IDPresentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltipopresentacion')),
                ('IDProveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproveedores')),
            ],
        ),
        migrations.CreateModel(
            name='tblDetalleMovAnimales',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDFolio', models.CharField(max_length=150, null=True)),
                ('Cantidad', models.IntegerField(null=True)),
                ('IDAnimales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblanimalestipo')),
            ],
        ),
        migrations.CreateModel(
            name='tblDetalleAnimales',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=15, null=True)),
                ('Fecha', models.DateTimeField(null=True)),
                ('Peso', models.FloatField(null=True)),
                ('NoPartida', models.IntegerField(null=True)),
                ('No_Guia', models.IntegerField(null=True)),
                ('IDAnimal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblanimalestipo')),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblclientes')),
                ('IDCorral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcorrales')),
            ],
        ),
        migrations.AddField(
            model_name='tblcorrales',
            name='IDEstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus'),
        ),
        migrations.AddField(
            model_name='tblcontenedoresproductos',
            name='IDCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproveedores'),
        ),
        migrations.AddField(
            model_name='tblcontenedoresproductos',
            name='IDEstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus'),
        ),
        migrations.AddField(
            model_name='tblcontenedoresmateriaprima',
            name='IDEstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus'),
        ),
        migrations.CreateModel(
            name='tblAsignaCorrales',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=15, null=True)),
                ('Fecha', models.DateTimeField(max_length=150, null=True)),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblclientes')),
                ('IDCorral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcorrales')),
                ('TipoMov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltipomov')),
            ],
        ),
        migrations.AddField(
            model_name='tblanimalestipo',
            name='IDEstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus'),
        ),
    ]
