# Generated by Django 4.2.1 on 2024-05-30 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblProductoMovimientos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDFolio', models.CharField(max_length=15, null=True)),
                ('Fecha', models.DateField(null=True)),
                ('cantidad', models.FloatField(null=True)),
                ('notas', models.CharField(max_length=120, null=True)),
                ('IDProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblproductos')),
                ('TipoMov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tbltipomov')),
            ],
        ),
        migrations.CreateModel(
            name='tblMPMovimientos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(null=True)),
                ('cantidad', models.FloatField(null=True)),
                ('IDFolio', models.CharField(max_length=15, null=True)),
                ('IDMateriaPrima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblmateriaprima')),
            ],
        ),
    ]
