# Generated by Django 4.2.1 on 2024-05-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_tblproductomovimientos_tblmpmovimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEventosValmoSys',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Productos', models.BooleanField(null=True)),
                ('Recetas', models.BooleanField(null=True)),
                ('MateriaPrima', models.BooleanField(null=True)),
            ],
        ),
    ]
